### ISSUE TITLE
I cannot use sFIFO in my main loop?  

### ISSUE THREAD

**Issue by synaption** [rambo/SimpleFIFO#4]
I get error: 'sFIFO' was not declared in this scope, even though it works in the setup loop?

**Comment by rambo** [comment]
Post your code to gist and I can take a look

**Comment by synaption** [comment]
all I had to do was move the "SimpleFIFO<int,10> sFIFO; //store 10 ints" up to the top out of the startup loop.

**Comment by rambo** [comment]
ah of course, global variables must be introduced in the global scope, not inside a function (like setup())
